import React from 'react';
import palette from '../styles/palette';

const Spinner = () => {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" style={{ background: 'none', display: 'block', shapeRendering: 'auto' }} width="70px" height="70px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
      <circle cx="50" cy="50" r="30" strokeWidth="2" stroke={palette.primary} strokeDasharray="47.12388980384689 47.12388980384689" fill="none" strokeLinecap="round">
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1.6666666666666667s" keyTimes="0;1" values="0 50 50;360 50 50" />
      </circle>
      {/* [ldio] generated by https://loading.io/ */}
    </svg>
  )
};


export default Spinner;
